apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.projectName }}
  namespace: ${{ values.projectName }}
  labels:
    app.kubernetes.io/name: ${{ values.projectName }}
    entity-id: ${{ values.projectName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ${{ values.projectName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${{ values.projectName }}
        entity-id: ${{ values.projectName }}
    spec:
      containers:
        - name: apache
          image: httpd:2.4-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web-content
              mountPath: /usr/local/apache2/htdocs/index.html
              subPath: index.html
      volumes:
        - name: web-content
          configMap:
            name: ${{ values.projectName }}-web
