apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.projectName }}
  namespace: ${{ values.projectName }}
  labels:
    app.kubernetes.io/name: ${{ values.projectName }}
    entity-id: ${{ values.projectName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ${{ values.projectName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${{ values.projectName }}
        entity-id: ${{ values.projectName }}
    spec:
      containers:
        - name: app
          image: httpd:2.4-alpine
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
