apiVersion: v1
kind: Service
metadata:
  name: ${{ values.projectName }}
  namespace: ${{ values.projectName }}
  labels:
    app.kubernetes.io/name: ${{ values.projectName }}
spec:
  selector:
    app.kubernetes.io/name: ${{ values.projectName }}
  ports:
    - port: ${{ values.servicePort }}
      targetPort: 80
      protocol: TCP
  type: ClusterIP
