apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}
  namespace: ${{ values.name }}
  labels:
    app.kubernetes.io/name: ${{ values.name }}
spec:
  selector:
    app.kubernetes.io/name: ${{ values.name }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
