ingress:
  tls:
    secretName: "backstage-kr-server-tls"
backstage:
  appConfig:
    app:
      title: ALREADY11 Backstage
    organization:
      name: ALREADY11
  image:
    registry: ghcr.io
    repository: SAMJOYAP/backstage-app
    tag: 95fc92721dbf7950a4b96fb5dd3c9beb15a779a5
