ingress:
  tls:
    secretName: "backstage-already11-server-tls"
backstage:
  appConfig:
    app:
      title: ALREADY11 Backstage
    organization:
      name: ALREADY11
  image:
    registry: 710232982381.dkr.ecr.ap-northeast-2.amazonaws.com
    repository: backstage-already11
    tag: 1.0.1
serviceAccount:
  name: backstage-already11
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::710232982381:role/backstage-already11-irsa-role
